"""Regenerate browser policies after editing inline scripts; --check is CI-safe."""
import argparse, base64, hashlib, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SDK = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.3/dist/umd/supabase.js'
API = 'https://lgdjxwjwfpjpdbkljywn.supabase.co'
def policy(source):
    hashes=[]
    for attrs, body in re.findall(r'<script\b([^>]*)>(.*?)</script\s*>',source,re.S|re.I):
        if not re.search(r'\bsrc\s*=',attrs,re.I):
            hashes.append("'sha256-"+base64.b64encode(hashlib.sha256(body.encode()).digest()).decode()+"'")
    return '; '.join(["default-src 'none'", "script-src 'self' "+' '.join(hashes+([SDK] if SDK in source else [])), "script-src-attr 'none'", "style-src 'self' 'unsafe-inline'", "img-src 'self' data:", "font-src 'self'", "connect-src 'self'"+(' '+API if 'cloud-save.js' in source else ''), "media-src 'self'", "frame-src 'none'", "object-src 'none'", "base-uri 'none'", "form-action 'self'"])
def updated(source):
    source=re.sub(r'\s*<!-- Browser security policy:.*?<!-- /Browser security policy -->', '',source,flags=re.S)
    tags='\n    <!-- Browser security policy: generated by scripts/security_policy.py -->\n    <meta http-equiv="Content-Security-Policy" content="'+policy(source)+'">\n    <meta name="referrer" content="strict-origin-when-cross-origin">\n    <!-- /Browser security policy -->'
    return re.sub(r'(<head\b[^>]*>)',lambda m:m[1]+tags,source,count=1,flags=re.I)
if __name__=='__main__':
    check=argparse.ArgumentParser();check.add_argument('--check',action='store_true');args=check.parse_args();bad=[]
    for path in ROOT.rglob('*.html'):
        if '.git' in path.parts:continue
        old=path.read_text();new=updated(old)
        if old!=new:
            if args.check:bad.append(str(path.relative_to(ROOT)))
            else:path.write_text(new)
    if bad:raise SystemExit('Regenerate security policies: '+', '.join(bad))
    print('Browser security policies verified.' if args.check else 'Browser security policies generated.')
